server:
  port: 8080

spring:
  # H2 Console: /h2-console
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.106.0:5432/test-db
    platform: postgres
    username: postgres
    password: Mobigen.07$
    #hikari:
      #jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;
      #username: sa
      #password:
      #driver-class-name: org.h2.Driver


  #h2:
  #  console:
  #    enabled: true

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
